// Code generated by protoc-gen-go.
// source: GrpcDemoService.proto
// DO NOT EDIT!

/*
Package GrpcDemoService is a generated protocol buffer package.

It is generated from these files:
	GrpcDemoService.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package GrpcDemoService

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	ReturnString string `protobuf:"bytes,1,opt,name=returnString" json:"returnString,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetReturnString() string {
	if m != nil {
		return m.ReturnString
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "GrpcDemoService.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "GrpcDemoService.HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GrpcDemoService service

type GrpcDemoServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type grpcDemoServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcDemoServiceClient(cc *grpc.ClientConn) GrpcDemoServiceClient {
	return &grpcDemoServiceClient{cc}
}

func (c *grpcDemoServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/GrpcDemoService.GrpcDemoService/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GrpcDemoService service

type GrpcDemoServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterGrpcDemoServiceServer(s *grpc.Server, srv GrpcDemoServiceServer) {
	s.RegisterService(&_GrpcDemoService_serviceDesc, srv)
}

func _GrpcDemoService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcDemoServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GrpcDemoService.GrpcDemoService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcDemoServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcDemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GrpcDemoService.GrpcDemoService",
	HandlerType: (*GrpcDemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GrpcDemoService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "GrpcDemoService.proto",
}

func init() { proto.RegisterFile("GrpcDemoService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x75, 0x2f, 0x2a, 0x48,
	0x76, 0x49, 0xcd, 0xcd, 0x0f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x47, 0x13, 0x56, 0x52, 0xe2, 0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x8c, 0xb9, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x94, 0xb8, 0x78, 0x8a, 0x52, 0x4b, 0x4a, 0x8b, 0xf2, 0x82, 0x4b, 0x8a, 0x32,
	0xf3, 0xd2, 0xa1, 0x8a, 0x51, 0xc4, 0x8c, 0xa2, 0xb9, 0xd0, 0xed, 0x12, 0xf2, 0xe0, 0x62, 0x05,
	0x9b, 0x23, 0x24, 0xab, 0x87, 0xee, 0x3a, 0x64, 0x37, 0x48, 0xc9, 0xe1, 0x92, 0x86, 0x58, 0xaf,
	0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x9a, 0x69, 0xb6,
	0xe6, 0x00, 0x00, 0x00,
}
